### ISSUE TITLE
complains there is no market data file available - it's there and readable

### ISSUE THREAD

**Issue by JDJoe** [EDCD/EDMarketConnector#2329]
complains there is no market data JSON file available - it's there and readable.

**Comment by Rixxan** [comment]
Hey there @JDJoe! Apologies for the delay in getting back to you. 

Can you provide screenshots, log files, or the like to help diagnose this report? There's lots of reasons this message could appear, but I can't tell why exactly without more information.

**Comment by Takios** [comment]
I'd been getting the same error message, but I'm on Linux so not sure if it's the same issue that the reporter is facing.

This is from the logfile:

```
2024-12-19 19:19:19.496 UTC - DEBUG - 70532:140445234963840:70532 plugins.eddn.journal_entry:2556: Failed exporting Market
Traceback (most recent call last):
  File "/home/MYUSERNAME/Downloads/EDMarketConnector-Release-5.12.1/plugins/eddn.py", line 2536, in journal_entry
    with path.open('rb') as f:
         ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '~/Spiele/samsung1/SteamLibrary/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved Games/Frontier Developments/Elite Dangerous/Market.json'
```

Notice the `~` at the beginning of the path. On Linux it should expand to the user's home directory, but in this case it is not expanded. I fixed the issue on my system by replacing the `~` with the direct path of my home directory in the EDMarketConnector.ini.

**Comment by JDJoe** [comment]
Probably related: 

 WARNING - 10966:124345655114624:10966 journal_lock.JournalLock.open_journal_dir_lockfile:69: Couldn't open "**~**/.steam/debian-installation/.../edmc-journal-lock.txt" for "w+" Aborting duplicate process checks: FileNotFoundError(2, 'No such file or directory')

**Comment by Rixxan** [comment]
Probably related to #1494 if I had to guess. Will investigate.

**Comment by Rixxan** [comment]
I'm going to mark this as duplicate, as it appears to be the same as #1494 which is staged for 5.13. If for whatever reason 5.13 does not fix this issue, please reopen.
